# Generated by Django 5.1.3 on 2024-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('RF', 'Refunded'), ('CP', 'Completed'), ('CN', 'Cancelled')], max_length=255),
        ),
    ]
